<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Lamar.Microsoft.DependencyInjection" Version="14.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.KeyPerFile" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.2" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Lib\Core.Lib.csproj" />
  </ItemGroup>

</Project>
