<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Duende.IdentityModel" Version="7.0.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.2" />

    <PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="8.0.0" />

    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>
  
</Project>
