<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CorrelationId" Version="3.0.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\Core.App.csproj" />
    <ProjectReference Include="..\Lib.Web\Core.Lib.Web.csproj" />
  </ItemGroup>
  
</Project>
