<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CorrelationId" Version="3.0.1" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\App\Core.App.csproj" />
    <ProjectReference Include="..\Lib.Web\Core.Lib.Web.csproj" />
  </ItemGroup>
  
</Project>
